import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const {data, isLoading }  = api.course.getAll.useQuery();
  console.log(data)
  if(isLoading) return <div> Loading... </div>
  if(!data) return <div> No data for this course </div>
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
     </Head>
     <main className="flex justify-center h-screen "> 
     <div className="bg-red-200 h-full w-full md:max-w-7xl border-x">
      <div> Orientation </div>
      <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Check!</button>
      </div>
          <div>
            <p> Hey</p>
              {data?.map((post) => (
              <div key={post.id}>{post.content} </div>))
            }
          </div>
      </main>
    </>
  );
}
